### ISSUE TITLE
Reduce requests

### ISSUE THREAD

**Issue by Brojowski** [surprisetech/intheloop#19]
This switch statement actually runs all of the queries at once. We only want the one input query to run.

	switch = {"new":newPosts(sr),
			   "hot":hotPosts(sr),
			   "topalltime":topPostsAllTime(sr),
			   "top24hrs":topPostsPast24Hours(sr),
			   "controversalall":controversalPast24Hours(sr),
			   "controversal24hrs":controversalPast24Hours(sr),
	}

**Comment by krichardson864** [comment]
Plan A: 
   Step 1 : check if lambda's optimize (use print statements)
   Step 2 : make switch dictionaries global if lambda works.
Plan B:
   Just write a bunch of ugly else if statements

**Comment by Brojowski** [comment]
Generalize this to work with subreddits, users etc
