### ISSUE TITLE
Make url routes more descriptive

### ISSUE THREAD

**Issue by Brojowski** [surprisetech/intheloop#24]
Right now, the routes all start the same

subreddit: /count/{sr}/{time-modifier}
user: /count/{uname}

make the names more descriptive, along the lines of 
subreddit: /subreddit/{sr}/{time-modifier}
user: /user/{uname}

**Comment by snwbrds2922** [comment]
Will change url's to reddit url format. /u/ for count users, /r/ for subreddit

**Comment by Brojowski** [comment]
Closed by 9ef41da317d7fec832029b7832bc6137f89caadc
